export { AegisClient, AegisClientConfig } from './client';
export { ComplianceModule } from './compliance';
export { AssetModule } from './asset';
export { InvestorModule } from './investor/portfolio';
export { RoleModule } from './role';
export { parseSorobanResult } from './utils/xdr-parser';
export * from './types/portfolio';
export * from './errors/portfolio';
export * from './types/role';
export * from './errors/role';